### ISSUE TITLE
Mod Interaction: Twilight Forest mobs being caught in MineFactoryReloaded Safari Nets causing crashes

### ISSUE THREAD

**Issue by Techokami** [Benimatic/twilightforest#13]
As of the most recent release on teamcofh.com, Twilight Forest mobs caught with MineFactoryReloaded Safari Nets will crash the game when looked at.
[Here is the crash log.](http://pastebin.com/VMdfQ83C) It appears to be a case of nonstandard spawn egg shenanigans (which explains why the captured mobs were uncolored before the update...)

**Comment by Benimatic** [comment]
Closing as this has been resolved
