### ISSUE TITLE
B:EnforcedProgression=false Not Working

### ISSUE THREAD

**Issue by DatenThielt** [Benimatic/twilightforest#17]
We have EnforcedProgression on our Server switched to false, Unfortunately this has had no effect at all and our players still report they cant interact with 90% of buildings/mobs within the twilight Forrest, They just get the force field effect.  Any help would be great

**Comment by Ogliss** [comment]
same issue, it doesnt seem to respect any changes to the config

**Comment by bookerthegeek** [comment]
Any work done on this? Still an issue in the latest versions.

**Comment by Benimatic** [comment]
In the latest versions this option is a game rule, rather than a config flag.
