### ISSUE TITLE
Spawn Surrounded By Debuff Biomes

### ISSUE THREAD

**Issue by cyberdragon442** [Benimatic/twilightforest#18]
I totally dislike the idea of debuff biomes. I find it pointless, considering they are just annoyances and do not allow any "progression" because it makes it hard to get anywhere. This is especially true on the server I play on given that the twilight spawn seems totally surrounded by them making it nearly impossible to leave. The only way to get around the twilight now is flying or major buffing gear. You could even spawn on one given the random spawns. The Highlands doesn't even hurt you, it just makes annoying lava/burning noises so we have to leave through this one.

I understand that it can be turned off in the configuration. I am simply voicing my opinion as to why this particular aspect should be removed. If you want "progression" just don't let the boss monsters spawn when you haven't beaten the previous one.

**Comment by Benimatic** [comment]
Closing as this is a matter of opinion.
