### ISSUE TITLE
Twilight forest for minecraft 1.8

### ISSUE THREAD

**Issue by McBossKiller** [Benimatic/twilightforest#19]
forge has came out for minecraft 1.8 and i was hoping twilight forest would soon update to the new minecraft forge version.

**Comment by Yulife** [comment]
Stop going through every mod's repository and asking for 1.8 via an issue, seriously.
You have no influence whether it updates or not, it is up to the mod author when and if they update to 1.8.
Stop wasting people's time and play on.
