### ISSUE TITLE
Ars Magica mobs in Twilight Forest

### ISSUE THREAD

**Issue by CrowAU** [Benimatic/twilightforest#20]
Ars Magica mobs spawn in the twilight forest when Witchery is present, the author of witchery said it maybe caused by Ars Magica or Twilight so I've posted this on both here and Ars Magica github.

Currently running MC 1.7.10 on Forge 1.7.10-10.13.2.1.1291
Mods; 
1.7.10_AM2-1.4.0.008
AnimationAPI-1.7.10-1.2.4
twilightforest-1.7.10-2.3.3
witchery-1.7.10-0.22.0

**Comment by Benimatic** [comment]
Closing as this is old and I think it's been resolved.
