### ISSUE TITLE
Server crash - twilightforest.world.TFGenWitchHut.generateTinyHut

### ISSUE THREAD

**Issue by ProsperCraft** [Benimatic/twilightforest#32]
http://pastebin.com/hfyWxqDY

Another - http://pastebin.com/LuyWwUBt
Another - http://pastebin.com/K7YZRmEw

FTB Modpack Infinity v 1.6.2

**Comment by ProsperCraft** [comment]
This is still an issue in FTB Infinity 1.10.1

http://pastebin.com/eq0ser0Z

**Comment by Benimatic** [comment]
I think this has been fixed at either the extrautils or the modpack level since then.
