### ISSUE TITLE
Biome ID conflict

### ISSUE THREAD

**Issue by CitiesXL2815** [Benimatic/twilightforest#36]
[Twilight forest] Biome ID conflict detected. Fix by editing the config file.

I need help with ID in the config?

**Comment by CitiesXL2815** [comment]
https://gist.github.com/CitiesXL2815/4daddfd94bd6ffdd45bb

**Comment by trollworkout** [comment]
loook for a mod called no id conflicts mod that lists out all the unused biome ids

**Comment by CitiesXL2815** [comment]
thx

**Comment by trollworkout** [comment]
i think nei can also dump all biome ids
