### ISSUE TITLE
Disabled Ores generate in the TF

### ISSUE THREAD

**Issue by Zsashas** [Benimatic/twilightforest#41]
I have disabled most ores in my pack except the variants from Immersive Engineering if they exist, however I am still finding Forestry Copper and Tin and Hydraulicraft Copper in the Twilight Forest. There may be others generating, but those are what I have found so far.

**Comment by hron84** [comment]
@Zsashas Can you explain how did you disabled ores? CoFHCore can do an effective work to disable most of the ores.

**Comment by Zsashas** [comment]
Using the config files. I don't have any CoFH mods.

**Comment by hron84** [comment]
I think Twilight can control ores it know. Try using CoFHCore for this, as it is the best mod to control oregen. You don't need any other CoFH mod to support just controlling oregen, so no ThermalExpansion or RSA needed to be installed, only CoFHCore.

**Comment by Zsashas** [comment]
I shouldn't need another mod for this, though. TF shouldn't be generating blocks that are disabled. That's the issue.

**Comment by Benimatic** [comment]
Twilight Forest doesn't directly generate any non-vanilla ores.

**Comment by Zsashas** [comment]
If the ores are disabled in the respective mod configs, then why are they still appearing in the forest?

**Comment by Benimatic** [comment]
I guess I don't know why they're appearing, but I certainly have no reference to any ores from other mods.
